### ISSUE TITLE
Question on Code snippet 

### ISSUE THREAD

**Issue by Pauldro** [thomasaull/RestApi#13]
Do you know where I can find the Benjamin Milde code for using FastRoute with PW?

**Comment by thomasaull** [comment]
@Lostkobrakai could you give me a hand here? I remember you saved it as a gist, but I can‘t find it anymore

**Comment by LostKobrakai** [comment]
I quick search though my gists/repos yielded nothing. It's been years, so I can't really help much more than that.

**Comment by thomasaull** [comment]
@LostKobrakai Thanks anyway!
@Pauldro I'm afraid you'll have to extract the bits you need from this file: https://github.com/thomasaull/RestApi/blob/master/Router.php
