### ISSUE TITLE
Status codes

### ISSUE THREAD

**Issue by MrSnoozles** [thomasaull/RestApi#4]
Hello and thank you for the module.

Is it possible already to modify the status code to something other than 200? I couldn't find anything regarding this in the documentation.

Regards

**Comment by thomasaull** [comment]
@MrSnoozles Yes it's possible. If it's an error you can use something like this anywhere in your code:
```
throw new \Exception('Not found', 404);
```
In case it's not an error you can just modify the response code before you return your response:
```
http_response_code(201);
return $response;
```

Let me know if this solves your question
