### ISSUE TITLE
Error: Trying to access array offset on value of type null :: Router.php:286

### ISSUE THREAD

**Issue by spoetnik** [thomasaull/RestApi#6]
A clean install, and I get this error. 
`{"error":"Error: Trying to access array offset on value of type null. File: \/usr\/local\/apache2\/api\/site\/modules\/RestApi\/Router.php:286"}`

Strange because I have used this same version of the module before, without any problems.

Can you please help me, of give a direction to debug it myself?

**Comment by spoetnik** [comment]
Diggin into this, it seems like the module is not yet php 7.4 compatible.

This fixes it, but I'm not sure if this is right...

`  public static function handleFatalError() {
    if (error_get_last()!==null){
      $last_error = error_get_last();
        if ($last_error['type'] === E_ERROR) {
          // fatal error
          self::handleError(E_ERROR, $last_error['message'], $last_error['file'], $last_error['line']);
        }
      }
  }`

**Comment by csaggo** [comment]
I did a similar fix for PHP 7.4 

changed 
`if ($last_error['type'] === E_ERROR) {`
to
`if ($last_error && $last_error['type'] === E_ERROR) {`

Is the Module still in active development @thomasaull  ? Its a great API-Starter for sure! If you need contributions please let us know

**Comment by thomasaull** [comment]
Hey @spoetnik, @csaggo 

thanks for your issue and solving the problem. I just released v0.0.7 which contains the fix by @csaggo. 

Regarding your question: Yes in theory the module is still in active development, my resources over the last year have been kind of limited though. I try my best to offer support and provide fixes for critical things like this issue. However there are two interesting PRs laying around for quite some time now, which I haven't had time to look into (#3 is adding basic-auth by @flydev-fr, #5 adds a lot of new functionality (better jwt-handling, multiple api keys and much more) by @Sebiworld). It's a pity theses aren't integrated yet. So if anyone of you guys have time to do a first code review of those I'd be very thankful :)

**Comment by thomasaull** [comment]
I'm going to close this issue for now, feel free to re-open if there's any problems with the new release!
